apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: secret-a
  namespace: test-trade-secrets
data:
  value1: U29tZSBvdGhlciB2YWx1ZQ==
  value2: U29tZSBjb21wbGV0ZWx5IG90aGVyIHZhbHVl
  value3: Y2Nj
